### PR TITLE
Add fallback to domain when searching

### LINKED ISSUE #4: Hostname fallback when searching
Some websites use www.[domain].[tld] as their hostnames and other have special hostnames for login like accounts.[domain].[tld]. I'd like to store the passwords for them without the prefixes, but just the domain. The addon doesn't find the passwords then because the hostname doesn't match exactly. Is it possible to support such a fallback to the domain? Maybe with a config option?

### PR DESCRIPTION
**Pull request by mjanser**
Fixes #4

### CODE REVIEW

**Comment by untitaker** [comment]
:+1:

**Comment by gekmihesg** [comment]
I like the idea, but I would feel safer to strip a predefined list of host names only, like `www,account,accounts,login`. Otherwise you might leak passwords from the wrong site. Also, with a predefined list it is possible to store new entries in the shortened location. I've implemented this here: 87362fa73b8b80c40bc14906782208813a6c166d
Does this work for you?

**Comment by untitaker** [comment]
Sounds fine as well!

**Comment by mjanser** [comment]
This solution is fine for me as well.

**Comment by gekmihesg** [comment]
Merged 87362fa, [released](https://github.com/gekmihesg/pass-manager/releases/tag/v0.6.0) and [submitted for verification](https://addons.mozilla.org/en-US/firefox/addon/pass-manager/versions/0.6.0).

**Pull request closed without merging**
